on:
  push:
    branches:
      - main  # Ensure you are using the correct branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Ensure this matches your project

      - name: Restore dependencies
        run: dotnet restore IMS.sln  # Restore the solution instead of the deleted IMS project

      - name: Build
        run: dotnet build IMS.sln --configuration Release --no-restore  # Build the solution

  test:
    runs-on: ubuntu-latest
    needs: build  # This ensures the test job runs after the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Ensure this matches your project

      - name: Restore dependencies
        run: dotnet restore IMSTests/IMSTests.csproj  # Restore the test project

      - name: Run Tests
        run: dotnet test IMSTests/IMSTests.csproj --no-restore --verbosity normal  # Run tests

  frontend-tests:
    runs-on: ubuntu-latest
    needs: build  # This ensures the frontend-tests job runs after the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Ensure this matches your project requirements

      - name: Install dependencies
        run: npm install
        working-directory: ims-frontend  # Set the working directory to ims-frontend

      - name: Run unit and integration tests
        run: npm test
        working-directory: ims-frontend  # Set the working directory to ims-frontend

      - name: Start the application
        run: npm start &
        env:
          CI: true
        working-directory: ims-frontend  # Set the working directory to ims-frontend

      - name: Run end-to-end tests
        run: npx cypress run
        working-directory: ims-frontend  # Set the working directory to ims-frontend