name: CI Pipeline

on:
  push:
    branches:
      - main  # Use 'main' if that's your default branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore IMS/IMS.csproj

      - name: Build
        run: dotnet build IMS/IMS.csproj --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test IMSTests/IMSTests.csproj --no-restore --verbosity normal
