name: CI Pipeline

on:
  push:
    branches:
      - main  # Ensure you are using the correct branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Ensure this matches your project

      - name: Restore dependencies
        run: dotnet restore IMS.sln  # Restore the solution instead of the deleted IMS project

      - name: Build
        run: dotnet build IMS.sln --configuration Release --no-restore  # Build the solution

  test-itemspage:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'  # Ensure this matches your project

      - name: Install dependencies
        run: npm install

      - name: Run ItemsPage test
        run: npm test -- src/pages/ItemsPage.test.tsx