name: CI Pipeline

on:
  push:
    branches:
      - main  # Ensure you are using the correct branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Ensure this matches your project

      - name: Restore dependencies
        run: dotnet restore IMS/IMS.csproj

      - name: Build
        run: dotnet build IMS/IMS.csproj --configuration Release --no-restore
